title: 我的个人日记
description: 记录生活点滴，分享学习心得
author: MingXuan
email: your-email@example.com
baseurl: ""
url: "https://username.github.io" # 替换为你的实际GitHub Pages URL

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 默认配置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "MingXuan"

# 时区
timezone: Asia/Shanghai

# 语言设置
lang: zh-CN